name: Test deployment

on:
  pull_request:
    branches: [main, development]
    paths: [docs/**]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          cache: yarn
      - name: Test build
        working-directory: docs
        run: |
          yarn install
          yarn build